// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3D1o_uLgkv8Hce8ydzME5CEO7dj9-8bA',
    appId: '1:878910233338:web:a86db5532c73371ae68743',
    messagingSenderId: '878910233338',
    projectId: 'evently-app-1223c',
    authDomain: 'evently-app-1223c.firebaseapp.com',
    storageBucket: 'evently-app-1223c.firebasestorage.app',
    measurementId: 'G-ZL350CHD21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYWf8MrYMp12WDvNyXpiuakeaTwyjC_A',
    appId: '1:878910233338:android:1e0fc37708e4592fe68743',
    messagingSenderId: '878910233338',
    projectId: 'evently-app-1223c',
    storageBucket: 'evently-app-1223c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMSDkQUuMtqUinIIqi0crlnAhfV-PDus0',
    appId: '1:878910233338:ios:5f73477df83bfe35e68743',
    messagingSenderId: '878910233338',
    projectId: 'evently-app-1223c',
    storageBucket: 'evently-app-1223c.firebasestorage.app',
    iosBundleId: 'com.example.eventsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMSDkQUuMtqUinIIqi0crlnAhfV-PDus0',
    appId: '1:878910233338:ios:5f73477df83bfe35e68743',
    messagingSenderId: '878910233338',
    projectId: 'evently-app-1223c',
    storageBucket: 'evently-app-1223c.firebasestorage.app',
    iosBundleId: 'com.example.eventsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3D1o_uLgkv8Hce8ydzME5CEO7dj9-8bA',
    appId: '1:878910233338:web:0badf60e4a721724e68743',
    messagingSenderId: '878910233338',
    projectId: 'evently-app-1223c',
    authDomain: 'evently-app-1223c.firebaseapp.com',
    storageBucket: 'evently-app-1223c.firebasestorage.app',
    measurementId: 'G-95JX9D86XB',
  );
}
